site_name: "Энциклопедия Мэйна"
site_url: https://my-world-wiki.netlify.app/
site_dir: public
nav:
  - "Главная": index.md
  - "О мире": 
    - "Космогония": world/cosmogony.md
    - "Планы Мэйна": world/planes.md
    - "География": world/geography.md
    - "Хронология": world/timeline.md
    - "Итейра": world/iteira.md
  - "Места": 
    - "Джадамар": locations/jadhamar.md
    - "Сарабант": locations/sarabant.md
    - "Вейлмарк": locations/veilmark.md
    - "Киельнира": locations/kielnira.md
    - "Гиннунга": locations/ginnunga.md
    - "Аланвэ": locations/alanve.md
  - "История":
    - "Северная война": history/northren_war.md
    - "Война трёх рас": history/three_races_war.md
  - "Расы":
    - "Список рас": race/0_list_race.md
    - "Люди": race/1_human.md
    - "Эйны": race/2_ein.md
    - "Талги": race/3_talg.md
    - "Тавры": race/4_taur.md
    - "Великаны": race/5_giant.md
    - "Стеннары": race/6_stennar.md
    - "Урсы": race/7_urs.md
    - "Ульфы": race/8_ulf.md
    - "Сетксар": race/9_setksar.md
    - "Ксар": race/10_ksar.md
  - "Существа":
    - "Крылатая почта": creatures/winged_mail.md 
    - "Аурохи": creatures/aurochs.md
    - "Аэлхи": creatures/aelchs.md
    - "Арахи": creatures/arach.md
    - "Бадри": creatures/badri.md
    - "Балхорны": creatures/balhorns.md
    - "Шорбалы": creatures/shorbals.md
  - "Персонажи":
    - "Небесные всадники": characters/sky_riders.md 
    - "Виглаф": characters/viglaf.md
  - "Другое": 
    - "Чёрный Край": other/black_region.md
    - "Книги": other/books.md
  - "Странная Система":
    - "Предисловие": strangesystem/0_strange_system.md
    - "Общие механики": strangesystem/1_system_general_mechanics.md
    - "Механика бросков": strangesystem/2_system_dice_rolls.md
    - "Ранения, усталость и стресс": strangesystem/3_system_injuries.md
    - "Модификаторы": strangesystem/4_system_modifiers.md
    - "Персонаж": strangesystem/5_system_character.md
    - "Таланты и изъяны": strangesystem/6_system_talents_flaws.md
    - "Баланс": strangesystem/7_system_balance.md
    - "Навыки": strangesystem/8_system_skills.md
    - "Социальные механики": strangesystem/9_system_social_mechanics.md
    - "Инвентарь и снаряжение": strangesystem/10_system_inventory.md
    - "Питомцы и другое имущество": strangesystem/11_system_pets_other.md
    - "Дополнительные механики": strangesystem/12_system_additional_mechanics.md
theme:
  name: material
  # Цвета
  palette:
    primary: white  # Доступные цвета: red, pink, purple, deep purple, blue, teal и т.д.
    accent: green
  # Шрифты
  font:
    text: Roboto  # Основной текст
    code: JetBrains Mono  # Код
  # Лого и фавиконка
  favicon: assets/favicon.ico
  logo: assets/logo.png

  # Расширенные настройки
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.logo
    #- header.autohide

plugins:
  - search
  - tags:  # Теги для статей


extra_css:
  - stylesheets/extra.css
